version: '3.4'
networks:
  dev:
    driver: bridge
services:
  backend-app:
    image: docker.io/library/backend-app
    depends_on:
     - "app_db"
    container_name: backend-app-container
    ports:
      - "5246:80"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=app_db;Port=5432;Database=Assignment; Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - AllowedOrigins=http://localhost:5173
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Assignment
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: